### PR TITLE
修复删除临时文件

### LINKED ISSUE #43: Upgrade Failed on Win32 Platform
When updating the version on the Win32 platform, an error is reported because the configuration file cannot be deleted. This project was created earlier for Linux, so compatibility with Windows platforms was not taken into account.

### PR DESCRIPTION
**Pull request by SakuraKy**

### CODE REVIEW

**Review by undefined-hestudio — COMMENTED** [review]
Please USE English backlog.

**Comment by undefined-hestudio** [comment]
```text
Uncaught ReferenceError ReferenceError: Cannot access 'logerr' before initialization
    at <anonymous> (c:\Users\undefined\Documents\code\not_hestudio\bing-wallpaper-get\get.js:38:7)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1565:14)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1708:10)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1318:32)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1128:12)
    at traceSync (<node_internals>/diagnostics_channel:322:14)
    at wrapModuleLoad (<node_internals>/internal/modules/cjs/loader:219:24)
    at executeUserEntryPoint (<node_internals>/internal/modules/run_main:170:5)
    at <anonymous> (<node_internals>/internal/main/run_main_module:36:49)
```

File: get.js [hunk 1]
```diff
@@ -31,7 +31,17 @@ if (!fs.existsSync(hbwgConfig.tempDir)) {
     !fs.existsSync(`${hbwgConfig.tempDir}/.version.hbwg_cache`) ||
     fs.readFileSync(`${hbwgConfig.tempDir}/.version.hbwg_cache`) != VERSION
   ) {
-    ChildProcess.execSync(`rm ${hbwgConfig.tempDir}/ -rf`);
+    try {
+      fs.rmSync(hbwgConfig.tempDir, { recursive: true, force: true });
+      logback("Temporary directory deleted successfully");
```
Comment (undefined-hestudio) [inline get.js]: please remove try...catch... and all log function use. user can get the wrong infomation from nodejs.

**Review by undefined-hestudio — APPROVED** [review]
